experiment:
    project: "generation"
    name: "alitok_xl" 
    max_train_examples: 1_281_167
    save_every: 50_000
    eval_every: 50_000
    generate_every: 5_000
    log_every: 1000
    log_grad_norm_every: 1_000
    resume: False 

model:
    vq_model:
        codebook_size:  4096
        token_size: 32
        num_latent_tokens: 273  
    
    generator:
        hidden_size: 1280
        num_hidden_layers: 32
        num_attention_heads: 16 
        dropout: 0.1
        attn_drop: 0.1
        tok_dropout: 0.1
        class_label_dropout: 0.1
        image_seq_len:  273  
        condition_num_classes: 1000

        # sampling hyper-params
        randomize_temperature: 1.0
        guidance_scale: 13.0
        guidance_scale_pow: 1.4
        use_checkpoint: False # True to save memory 
        seed: 2

dataset:
    params:
        # use pretokenized dataset for speed-up
        pretokenization:  'cache_alitok' 
        num_workers_per_gpu: 12
    preprocessing:
        resize_shorter_edge: 256
        crop_size: 256
        random_crop: False
        random_flip: True

optimizer:
    name: adamw 
    params:
        learning_rate: 4e-4
        beta1: 0.9
        beta2: 0.96
        weight_decay: 0.03

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 62_500 # 100 epochs with bsz 2048
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 32  #per GPU, total batch size 2048
    mixed_precision: "bf16"
    enable_tf32: True
    enable_wandb: True
    use_ema: False
    seed: 42
    max_train_steps: 250_000 # equal to 400 epochs
    max_grad_norm: 1.0